# Generated by Django 5.1.2 on 2024-11-17 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
