# Generated by Django 5.1.2 on 2024-11-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_enrollment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["name"],
                "verbose_name": "группа",
                "verbose_name_plural": "группы",
            },
        ),
    ]
